# Change these first
owner: Mineversal # Your GitHub organization or username, where this repository lives
repo: Mineversal-Status # The name of this repository

sites:
  - name: Mineversal
    url: https://mineversal.com
  - name: Mineversal Shortlink
    url: https://mineversal.org
  - name: Al-Jazari Virtual Assistant
    url: https://mineversal.net
  - name: Votie
    url: https://votie.mineversal.com
  #- name: IPv6 test
  #  url: forwardemail.net
  #  port: 80
  #  check: "tcp-ping"
  #  ipv6: true
  
assignees: # Users to assign downtime issues (optional)
  - AzharRizkiZ
  - AzharRizky

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.mineversal.com
  # baseUrl: /your-repo-name
  logoUrl: https://mineversal.com/assets/img/brand/default.png
  name: Mineversal Website Status
  introTitle: "**Mineversal** which can be interpreted as 'common property', is a new technology company founded & owned by Al Khwarizmi."
  introMessage: This is a status page which uses **real-time** data from our [Mineversal Status](https://github.com/Mineversal/Mineversal-Status). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Creator
      href: https://mineversal.com
  favicon: https://mineversal.com/assets/img/favicon.ico
  theme: light

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
